/content/documents/administration/configuration/local-environment:
  jcr:primaryType: hippo:handle
  jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
  jcr:uuid: 45278688-f372-4427-8e15-6b177cf51cc1
  hippo:name: Properties (Local Environment)
  hippo:versionHistory: 6290b8b2-b035-4045-a896-26238b3233be
  /local-environment[1]:
    jcr:primaryType: resourcebundle:resourcebundle
    jcr:mixinTypes: ['mix:referenceable']
    jcr:uuid: cafcb863-9c1f-4d5f-81d9-c652dc023fcd
    hippo:availability: []
    hippostd:retainable: false
    hippostd:state: draft
    hippostdpubwf:createdBy: admin
    hippostdpubwf:creationDate: 2021-02-05T15:37:26.056Z
    hippostdpubwf:lastModificationDate: 2022-05-31T18:12:59.062+01:00
    hippostdpubwf:lastModifiedBy: admin
    resourcebundle:descriptions: [Client Token for Instagram request, "Token that\
        \ identifies calls made to vs-dms-products as internal calls giving access\
        \ to wider data\r\n\r\nThis token is configured by the environment variable\
        \ VS_API_KEY, but it can be overriden here if needed.\r\n\r\nDo not commit\
        \ a value for this variable to the repository!!", App Id for Instagram request,
      "When this property is set to true it nullifies links.vs-dms-products.url AND\
        \ links.cms-base-path.url\r\n\r\nFor instance, this allows local environments\
        \ to use the default server (http://172.28.81.65:8089)  and feature environments\
        \ to use relative urls", "This path is prepend to the URL any time a non existing\
        \ URL needs to be composed.\r\n\r\nCan be nullified by links.use-relative-urls\r\
        \n\r\nlinks.use-relative-urls", "UI for vs-dms-products.\r\n\r\nThis value\
        \ will be used to compose urls to vs-dms-products and Canned Search", '',
      '', '', "Path of the Header & Footer endpoints which is used for identify URLs\
        \ able to process the override locale parameter (vs-locale-ctx)\r\n\r\nOverriding\
        \ the locale parameter allows to use a different language for the labels\r\
        \n\r\nTHE VALUE OF THIS PROPERTY DOES NOT CHANGE THE PATH OF THE ENDPOINTS"]
    resourcebundle:id: environment.local
    resourcebundle:keys: [instagram.accesstoken, dms-data.api-key, instagram.app-id,
      links.use-relative-urls, links.cms-base-path.url, links.vs-dms-products.url,
      dms-data.public-url, dms-data.private-url, youtube.api-key, data-internal.path]
    resourcebundle:messages: [0d41c47eaf42b43fe20de05201c798ec, $VS_DMS_PRODUCT_KEY,
      '1293271387429443', 'false', 'http://localhost:8080/site', 'http://172.28.81.65:8089',
      'http://172.28.81.65:8089/data', 'http://172.28.81.65:8089/data', $YOUTUBE_API_KEY,
      /site/data/internal]
  /local-environment[2]:
    jcr:primaryType: resourcebundle:resourcebundle
    jcr:mixinTypes: ['mix:versionable']
    jcr:uuid: 802cabcf-570b-4b96-a2f3-c57d595f9635
    hippo:availability: [preview]
    hippostd:retainable: false
    hippostd:state: unpublished
    hippostdpubwf:createdBy: admin
    hippostdpubwf:creationDate: 2021-02-05T15:37:26.056Z
    hippostdpubwf:lastModificationDate: 2022-05-31T18:14:09.429+01:00
    hippostdpubwf:lastModifiedBy: admin
    resourcebundle:descriptions: [Client Token for Instagram request, "Token that\
        \ identifies calls made to vs-dms-products as internal calls giving access\
        \ to wider data\r\n\r\nThis token is configured by the environment variable\
        \ VS_API_KEY, but it can be overriden here if needed.\r\n\r\nDo not commit\
        \ a value for this variable to the repository!!", App Id for Instagram request,
      "When this property is set to true it nullifies links.vs-dms-products.url AND\
        \ links.cms-base-path.url\r\n\r\nFor instance, this allows local environments\
        \ to use the default server (http://172.28.81.65:8089)  and feature environments\
        \ to use relative urls", "This path is prepend to the URL any time a non existing\
        \ URL needs to be composed.\r\n\r\nCan be nullified by links.use-relative-urls\r\
        \n\r\nlinks.use-relative-urls", "UI for vs-dms-products.\r\n\r\nThis value\
        \ will be used to compose urls to vs-dms-products and Canned Search", '',
      '', '', "Path of the Header & Footer endpoints which is used for identify URLs\
        \ able to process the override locale parameter (vs-locale-ctx)\r\n\r\nOverriding\
        \ the locale parameter allows to use a different language for the labels\r\
        \n\r\nTHE VALUE OF THIS PROPERTY DOES NOT CHANGE THE PATH OF THE ENDPOINTS"]
    resourcebundle:id: environment.local
    resourcebundle:keys: [instagram.accesstoken, dms-data.api-key, instagram.app-id,
      links.use-relative-urls, links.cms-base-path.url, links.vs-dms-products.url,
      dms-data.public-url, dms-data.private-url, youtube.api-key, data-internal.path]
    resourcebundle:messages: [0d41c47eaf42b43fe20de05201c798ec, $VS_DMS_PRODUCT_KEY,
      '1293271387429443', 'false', 'http://localhost:8080/site', 'http://172.28.81.65:8089',
      'http://172.28.81.65:8089/data', 'http://172.28.81.65:8089/data', $YOUTUBE_API_KEY,
      /site/data/internal]
  /local-environment[3]:
    jcr:primaryType: resourcebundle:resourcebundle
    jcr:mixinTypes: ['mix:referenceable']
    jcr:uuid: 058e53b1-cd96-4779-9ab4-944509c28427
    hippo:availability: [live]
    hippostd:retainable: false
    hippostd:state: published
    hippostdpubwf:createdBy: admin
    hippostdpubwf:creationDate: 2021-02-05T15:37:26.056Z
    hippostdpubwf:lastModificationDate: 2022-05-31T18:14:09.429+01:00
    hippostdpubwf:lastModifiedBy: admin
    hippostdpubwf:publicationDate: 2022-05-31T18:14:15.086+01:00
    resourcebundle:descriptions: [Client Token for Instagram request, "Token that\
        \ identifies calls made to vs-dms-products as internal calls giving access\
        \ to wider data\r\n\r\nThis token is configured by the environment variable\
        \ VS_API_KEY, but it can be overriden here if needed.\r\n\r\nDo not commit\
        \ a value for this variable to the repository!!", App Id for Instagram request,
      "When this property is set to true it nullifies links.vs-dms-products.url AND\
        \ links.cms-base-path.url\r\n\r\nFor instance, this allows local environments\
        \ to use the default server (http://172.28.81.65:8089)  and feature environments\
        \ to use relative urls", "This path is prepend to the URL any time a non existing\
        \ URL needs to be composed.\r\n\r\nCan be nullified by links.use-relative-urls\r\
        \n\r\nlinks.use-relative-urls", "UI for vs-dms-products.\r\n\r\nThis value\
        \ will be used to compose urls to vs-dms-products and Canned Search", '',
      '', '', "Path of the Header & Footer endpoints which is used for identify URLs\
        \ able to process the override locale parameter (vs-locale-ctx)\r\n\r\nOverriding\
        \ the locale parameter allows to use a different language for the labels\r\
        \n\r\nTHE VALUE OF THIS PROPERTY DOES NOT CHANGE THE PATH OF THE ENDPOINTS"]
    resourcebundle:id: environment.local
    resourcebundle:keys: [instagram.accesstoken, dms-data.api-key, instagram.app-id,
      links.use-relative-urls, links.cms-base-path.url, links.vs-dms-products.url,
      dms-data.public-url, dms-data.private-url, youtube.api-key, data-internal.path]
    resourcebundle:messages: [0d41c47eaf42b43fe20de05201c798ec, $VS_DMS_PRODUCT_KEY,
      '1293271387429443', 'false', 'http://localhost:8080/site', 'http://172.28.81.65:8089',
      'http://172.28.81.65:8089/data', 'http://172.28.81.65:8089/data', $YOUTUBE_API_KEY,
      /site/data/internal]
